repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^prometheus_novel/
      - id: ruff-format
        files: ^prometheus_novel/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --no-error-summary]
        files: ^prometheus_novel/(prometheus_lib|stages|interfaces)/
        additional_dependencies: [types-PyYAML, types-requests, pydantic]
        pass_filenames: false
        # Don't fail on mypy errors yet (many files need type hints)
        verbose: true
        always_run: false

