"""
WriterAI Seed Command - Flexible Story Idea Input

Supports three modes:
1. FULL MODE: Paste everything at once using the template
2. GUIDED MODE: Step-by-step with skip option (AI fills gaps)
3. MINIMAL MODE: Just give a one-liner, AI expands everything

The system shows you the complete template upfront so you know
exactly what you CAN provide - but nothing is required except
a basic idea.
"""

import os
import sys
import json
import asyncio
from pathlib import Path
from typing import Optional, Dict, Any
from dataclasses import dataclass, field
import argparse

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

try:
    import yaml
except ImportError:
    os.system(f"{sys.executable} -m pip install pyyaml")
    import yaml


# ============================================================================
# ANSI Colors
# ============================================================================

class C:
    H = '\033[95m'      # Header/Purple
    B = '\033[94m'      # Blue
    C = '\033[96m'      # Cyan
    G = '\033[92m'      # Green
    W = '\033[93m'      # Warning/Yellow
    R = '\033[91m'      # Red/Fail
    E = '\033[0m'       # End
    BOLD = '\033[1m'
    DIM = '\033[2m'


# ============================================================================
# The Complete Seed Template
# ============================================================================

FULL_TEMPLATE = """
================================================================================
                        WRITERAI STORY SEED TEMPLATE
================================================================================

Copy this template, fill in what you have, delete what you don't.
Paste the whole thing when prompted, or go step-by-step.

Lines starting with # are comments - delete them or leave them.
Empty sections will be auto-generated by AI.

--------------------------------------------------------------------------------
# REQUIRED - At minimum, give us SOMETHING to work with
--------------------------------------------------------------------------------

IDEA:
[Your story idea - can be one sentence or multiple paragraphs]
[Example: "A detective who can read memories discovers her own past was fabricated"]

--------------------------------------------------------------------------------
# OPTIONAL - The more you provide, the more control you have
--------------------------------------------------------------------------------

TITLE:
[Working title for your novel]

GENRE:
[Primary genre: sci-fi, fantasy, mystery, thriller, romance, horror, literary]
[Can include subgenres: "sci-fi noir", "romantic thriller", "dark fantasy"]

TONE:
[Examples: dark, hopeful, satirical, gritty, whimsical, literary, commercial]

TARGET_LENGTH:
[Examples: novella (30k), standard (60k), epic (100k+)]

--------------------------------------------------------------------------------
# WORLD & SETTING
--------------------------------------------------------------------------------

SETTING:
[Time period, location, atmosphere]
[Example: "Near-future Tokyo, 2089. Neon-lit corporate dystopia meets traditional temples"]

WORLD_RULES:
[What's possible/impossible in this world? Magic system? Technology level?]
[Example: "Memory reading requires physical contact. Memories can be bought/sold.
 The rich preserve memories in 'vaults'. The poor sell theirs to survive."]

KEY_LOCATIONS:
[Important places in your story]
[Example:
 - The Memory Exchange: Black market for memories
 - Vault 7: Secure facility for the elite's memories
 - The Blank District: Where memory-wiped people live]

--------------------------------------------------------------------------------
# CHARACTERS
--------------------------------------------------------------------------------

PROTAGONIST:
[Name, role, key traits, what they want, what's stopping them]
[Example: "Yuki Tanaka, 32, Memory Detective. Cold exterior, secretly afraid
 her own memories are fake. Wants truth about her past. Blocked by powerful
 people who benefit from her fabricated identity."]

ANTAGONIST:
[Who/what opposes the protagonist?]
[Example: "The Archivist - runs the Memory Exchange. Knows Yuki's real past.
 Uses that knowledge to manipulate her. Believes memories should be commodities."]

OTHER_CHARACTERS:
[Supporting cast - allies, rivals, love interests, mentors]
[Example:
 - Kenji: Yuki's partner, comic relief, secretly in love with her
 - Dr. Sato: Created the memory tech, now regrets it, becomes reluctant ally
 - The Ghost: Mysterious figure with no memories at all]

--------------------------------------------------------------------------------
# PLOT & STRUCTURE
--------------------------------------------------------------------------------

PREMISE:
[The central "what if" of your story]
[Example: "What if your entire identity was a lie designed to make you the
 perfect weapon, and discovering the truth meant becoming that weapon?"]

CENTRAL_CONFLICT:
[The main tension driving the story]
[Example: "Yuki must choose between the comfortable lie of her current life
 and the dangerous truth of who she really was."]

KEY_PLOT_POINTS:
[Major story beats you want to hit - as many or few as you have]
[Example:
 - Opening: Yuki reads a dying man's memory, sees her own face in his past
 - Inciting incident: She's hired to find someone who turns out to be herself
 - Midpoint: Discovers she was an assassin, her memories wiped and replaced
 - Low point: Her "partner" was assigned to watch her, not help her
 - Climax: Confronts the Archivist in Vault 7, must choose which self to be
 - Resolution: Destroys the memory technology, lives with fragmented identity]

SUBPLOTS:
[Secondary storylines]
[Example:
 - Romance: Growing feelings for Kenji despite knowing he was her handler
 - Mystery: Who ordered her memory wipe and why?
 - Theme: What makes us who we are - our memories or our choices?]

--------------------------------------------------------------------------------
# THEMES & DEEPER MEANING
--------------------------------------------------------------------------------

THEMES:
[What is this story really about?]
[Example: Identity, authenticity, the ethics of technology, found family,
 whether we can escape our past or must embrace it]

CENTRAL_QUESTION:
[The philosophical question your story explores]
[Example: "If our memories make us who we are, can we ever truly change?"]

MOTIFS:
[Recurring symbols or images]
[Example: Mirrors (reflection/identity), rain (washing away/cleansing),
 photographs (captured moments), locked doors (secrets)]

--------------------------------------------------------------------------------
# STYLE & VOICE
--------------------------------------------------------------------------------

WRITING_STYLE:
[How should this read?]
[Example: "Sparse, noir-influenced prose. Short punchy sentences during action.
 Longer, more reflective passages for emotional beats. First person present tense."]

INFLUENCES:
[Books, movies, shows that capture what you're going for]
[Example: "Blade Runner meets Memento, with the emotional depth of Never Let Me Go"]

AVOID:
[Things you don't want in your story]
[Example: "No love triangles. No chosen one prophecy. No amnesia as a cheap plot device
 (the amnesia IS the plot). No grimdark - keep some hope."]

--------------------------------------------------------------------------------
# STRATEGIC GUIDANCE (EDITORIAL / MARKET) - for publishers, savvy authors
# Sub-fields are parsed automatically: market_positioning, tropes,
# pacing_notes, dialogue_bank, aesthetic_guide, cultural_notes, commercial_notes
--------------------------------------------------------------------------------

STRATEGIC_GUIDANCE:
market_positioning:
[Target audience, comp titles, spice level, keywords]
[Example: "Contemporary romance. Comp titles: Beach Read, The Hating Game.
 Target: romance readers who want wit + emotional depth. Spice level: 3/5."]

tropes:
[Tropes to execute or subvert]
[Example: "Enemies-to-lovers, forced proximity, he-falls-first"]

pacing_notes:
[Act-by-act pacing guidance]
[Example: "Act 1 (25%): Setup, denial. Midpoint: first kiss. Act 3: crisis, resolution."]

dialogue_bank:
[Character voice notes, signature lines]
[Example:
 - Lena: sharp wit, legal metaphors, switches to Spanish when emotional
 - Marco: warm teasing, disarming sincerity, occasional Italian phrases]

aesthetic_guide:
[Visual palette, sensory descriptions, atmospheric details]
[Example: "Golden hour light, terracotta, deep blue sea, bougainvillea purple.
 Textures: rough stone, cool linen, salt spray."]

cultural_notes:
[Authentic details for world/culture]

commercial_notes:
[Series potential, mobile optimization, marketing hooks]

================================================================================
                              END OF TEMPLATE
================================================================================
"""

TEMPLATE_SECTIONS = [
    ("IDEA", "Your core story idea (required - everything else is optional)", True),
    ("TITLE", "Working title", False),
    ("GENRE", "Primary genre (sci-fi, fantasy, mystery, thriller, romance, literary)", False),
    ("TONE", "Overall tone (dark, hopeful, gritty, whimsical, etc.)", False),
    ("TARGET_LENGTH", "Novella (30k), standard (60k), or epic (100k+)", False),
    ("SETTING", "Time, place, atmosphere", False),
    ("WORLD_RULES", "What's possible/impossible in this world", False),
    ("KEY_LOCATIONS", "Important places in your story", False),
    ("PROTAGONIST", "Main character details", False),
    ("ANTAGONIST", "Opposition/villain", False),
    ("OTHER_CHARACTERS", "Supporting cast", False),
    ("PREMISE", "The central 'what if'", False),
    ("CENTRAL_CONFLICT", "Main tension driving the story", False),
    ("KEY_PLOT_POINTS", "Major story beats", False),
    ("SUBPLOTS", "Secondary storylines", False),
    ("THEMES", "What the story is really about", False),
    ("CENTRAL_QUESTION", "Philosophical question explored", False),
    ("MOTIFS", "Recurring symbols", False),
    ("WRITING_STYLE", "How it should read", False),
    ("INFLUENCES", "Similar works for reference", False),
    ("AVOID", "Things you don't want", False),
    ("STRATEGIC_GUIDANCE", "Editorial guidance: market positioning, tropes, pacing, dialogue, aesthetics", False),
]

# Sub-keys recognized inside the STRATEGIC_GUIDANCE block
_STRATEGIC_GUIDANCE_KEYS = [
    "market_positioning", "tropes", "pacing_notes", "dialogue_bank",
    "aesthetic_guide", "cultural_notes", "commercial_notes", "beat_sheet",
]


# ============================================================================
# Parsing Functions
# ============================================================================

def parse_template_input(text: str) -> Dict[str, str]:
    """Parse filled-in template text into a dictionary."""
    result = {}
    current_key = None
    current_value = []

    for line in text.split('\n'):
        line = line.rstrip()

        # Skip comments and separators
        if line.startswith('#') or line.startswith('===') or line.startswith('---'):
            continue

        # Check if this line is a key
        for key, _, _ in TEMPLATE_SECTIONS:
            if line.startswith(f"{key}:"):
                # Save previous key-value if exists
                if current_key and current_value:
                    result[current_key] = '\n'.join(current_value).strip()

                # Start new key
                current_key = key
                # Get value on same line if present
                value_on_line = line[len(key)+1:].strip()
                current_value = [value_on_line] if value_on_line else []
                break
        else:
            # Not a key line, add to current value
            if current_key is not None:
                current_value.append(line)

    # Don't forget the last key
    if current_key and current_value:
        result[current_key] = '\n'.join(current_value).strip()

    # Filter out placeholder text
    for key in list(result.keys()):
        value = result[key]
        if value.startswith('[') and value.endswith(']'):
            del result[key]
        elif not value or value.isspace():
            del result[key]

    return result


def validate_seed(seed_data: Dict[str, str]) -> tuple[bool, str]:
    """Validate that we have minimum required data."""
    idea = (seed_data.get('IDEA') or '').strip()
    if not idea:
        return False, "IDEA is required. Please provide at least a one-sentence story concept."
    if len(idea) < 3:
        return False, "IDEA is too short. Please provide at least a word or phrase for your story concept."
    return True, "Valid"


def _parse_strategic_guidance(text: str) -> Dict[str, str]:
    """Parse strategic guidance sub-fields from the STRATEGIC_GUIDANCE seed block.

    Recognises lowercase sub-keys (market_positioning, tropes, etc.) and
    collects multi-line values until the next sub-key or end of text.
    """
    result: Dict[str, str] = {}
    current_key: Optional[str] = None
    current_value: list[str] = []

    for line in text.split('\n'):
        stripped = line.strip()
        matched = False
        for key in _STRATEGIC_GUIDANCE_KEYS:
            if stripped.startswith(f"{key}:"):
                # Save previous sub-key
                if current_key and current_value:
                    result[current_key] = '\n'.join(current_value).strip()
                current_key = key
                value_on_line = stripped[len(key) + 1:].strip()
                current_value = [value_on_line] if value_on_line else []
                matched = True
                break
        if not matched and current_key is not None:
            current_value.append(line.rstrip())

    # Flush last sub-key
    if current_key and current_value:
        result[current_key] = '\n'.join(current_value).strip()

    # Drop empty / placeholder values
    return {
        k: v for k, v in result.items()
        if v and not v.isspace() and not (v.startswith('[') and v.endswith(']'))
    }


# ============================================================================
# Display Functions
# ============================================================================

def print_banner():
    print(f"""
{C.C}╔══════════════════════════════════════════════════════════════════════════════╗
║                                                                              ║
║   {C.BOLD}WRITERAI STORY SEED{C.E}{C.C}                                                         ║
║   {C.DIM}Transform your idea into a publication-ready novel{C.E}{C.C}                          ║
║                                                                              ║
╚══════════════════════════════════════════════════════════════════════════════╝{C.E}
""")


def print_template():
    """Print the full template for copying."""
    print(FULL_TEMPLATE)


def print_mode_menu():
    print(f"""
{C.H}Choose your input mode:{C.E}

  {C.G}1{C.E}) {C.BOLD}FULL MODE{C.E}     - See template, paste everything at once
  {C.G}2{C.E}) {C.BOLD}GUIDED MODE{C.E}   - Step-by-step prompts, skip any with Enter
  {C.G}3{C.E}) {C.BOLD}MINIMAL MODE{C.E}  - Just give your idea, AI does the rest

  {C.G}T{C.E}) {C.DIM}Show full template (for reference){C.E}
  {C.G}Q{C.E}) {C.DIM}Quit{C.E}
""")


def print_summary(seed_data: Dict[str, str]):
    """Print a summary of what was provided vs what AI will generate."""
    print(f"\n{C.H}{'='*60}{C.E}")
    print(f"{C.BOLD}SEED SUMMARY{C.E}")
    print(f"{C.H}{'='*60}{C.E}\n")

    provided = []
    ai_will_generate = []

    for key, description, required in TEMPLATE_SECTIONS:
        if key in seed_data and seed_data[key]:
            provided.append((key, description))
        else:
            ai_will_generate.append((key, description))

    print(f"{C.G}You provided ({len(provided)} items):{C.E}")
    for key, desc in provided:
        value_preview = seed_data[key][:60] + "..." if len(seed_data[key]) > 60 else seed_data[key]
        value_preview = value_preview.replace('\n', ' ')
        print(f"  {C.BOLD}{key}{C.E}: {C.DIM}{value_preview}{C.E}")

    print(f"\n{C.B}AI will generate ({len(ai_will_generate)} items):{C.E}")
    for key, desc in ai_will_generate:
        print(f"  {C.DIM}{key}: {desc}{C.E}")

    print(f"\n{C.H}{'='*60}{C.E}\n")


# ============================================================================
# Input Modes
# ============================================================================

def full_mode() -> Dict[str, str]:
    """Full mode - show template, accept paste."""
    print(f"\n{C.C}FULL MODE{C.E}")
    print(f"{C.DIM}Copy the template below, fill in what you have, paste it back.{C.E}")
    print(f"{C.DIM}Press Enter twice when done (empty line signals end).{C.E}\n")

    input(f"{C.W}Press Enter to see the template...{C.E}")
    print_template()

    print(f"\n{C.G}Now paste your filled template (Enter twice to finish):{C.E}\n")

    lines = []
    empty_count = 0
    while True:
        try:
            line = input()
            if line == '':
                empty_count += 1
                if empty_count >= 2:
                    break
                lines.append(line)
            else:
                empty_count = 0
                lines.append(line)
        except EOFError:
            break

    text = '\n'.join(lines)
    return parse_template_input(text)


def guided_mode() -> Dict[str, str]:
    """Guided mode - step by step with skip option."""
    print(f"\n{C.C}GUIDED MODE{C.E}")
    print(f"{C.DIM}Answer each prompt. Press Enter to skip (AI will fill it in).{C.E}")
    print(f"{C.DIM}For multi-line input, type 'DONE' on its own line when finished.{C.E}\n")

    seed_data = {}

    for key, description, required in TEMPLATE_SECTIONS:
        req_marker = f"{C.R}*{C.E}" if required else ""
        print(f"\n{C.B}{key}{C.E} {req_marker}")
        print(f"{C.DIM}{description}{C.E}")

        if key in ['IDEA', 'KEY_PLOT_POINTS', 'OTHER_CHARACTERS', 'WORLD_RULES',
                   'KEY_LOCATIONS', 'STRATEGIC_GUIDANCE']:
            # Multi-line input
            print(f"{C.DIM}(Multi-line: type 'DONE' when finished, or Enter to skip){C.E}")
            lines = []
            while True:
                line = input(f"{C.DIM}>{C.E} ")
                if line.upper() == 'DONE':
                    break
                if line == '' and not lines:
                    break  # Skip if first line is empty
                lines.append(line)
            value = '\n'.join(lines).strip()
        else:
            # Single line input
            value = input(f"{C.DIM}>{C.E} ").strip()

        if value:
            seed_data[key] = value
            print(f"{C.G}✓ Saved{C.E}")
        else:
            print(f"{C.DIM}↷ Skipped (AI will generate){C.E}")

    return seed_data


def minimal_mode() -> Dict[str, str]:
    """Minimal mode - just the idea."""
    print(f"\n{C.C}MINIMAL MODE{C.E}")
    print(f"{C.DIM}Just give us your story idea - one sentence to a few paragraphs.{C.E}")
    print(f"{C.DIM}AI will expand everything else.{C.E}")
    print(f"{C.DIM}Type 'DONE' on its own line when finished.{C.E}\n")

    print(f"{C.B}Your story idea:{C.E}")
    lines = []
    while True:
        line = input(f"{C.DIM}>{C.E} ")
        if line.upper() == 'DONE':
            break
        lines.append(line)

    idea = '\n'.join(lines).strip()

    # Optionally ask for genre
    print(f"\n{C.B}Genre?{C.E} {C.DIM}(Enter to let AI decide){C.E}")
    genre = input(f"{C.DIM}>{C.E} ").strip()

    seed_data = {'IDEA': idea}
    if genre:
        seed_data['GENRE'] = genre

    return seed_data


# ============================================================================
# Seed Expansion (AI-powered)
# ============================================================================

async def expand_seed(seed_data: Dict[str, str], llm_client=None) -> Dict[str, Any]:
    """Expand the seed data using AI to fill in missing pieces."""
    from prometheus_lib.llm.clients import get_client

    if llm_client is None:
        llm_client = get_client("gpt-4o-mini")

    # Build context from what we have
    provided_context = "\n".join([
        f"{key}: {value}"
        for key, value in seed_data.items()
    ])

    # Identify what needs to be generated (skip editorial fields — author-only)
    _SKIP_EXPANSION = {'STRATEGIC_GUIDANCE'}
    missing = [key for key, _, _ in TEMPLATE_SECTIONS
               if key not in seed_data and key not in _SKIP_EXPANSION]

    if not missing:
        print(f"{C.G}All sections provided - no AI expansion needed.{C.E}")
        return seed_data

    print(f"\n{C.B}Expanding seed with AI...{C.E}")
    print(f"{C.DIM}Generating: {', '.join(missing)}{C.E}\n")

    # Create expansion prompt
    prompt = f"""You are a master storyteller helping to develop a novel concept.

Based on the following provided story elements, generate the missing sections.
Be creative but consistent with what's been provided.

PROVIDED ELEMENTS:
{provided_context}

MISSING SECTIONS TO GENERATE:
{', '.join(missing)}

For each missing section, provide rich, specific, usable content.
Respond in this exact format (one section per block):

SECTION_NAME:
[Your generated content]

Generate all missing sections now:"""

    try:
        response = await llm_client.generate(prompt, max_tokens=4000, temperature=0.8)

        # Parse the AI response
        expanded = parse_template_input(response.content)

        # Merge with original (original takes precedence)
        for key, value in expanded.items():
            if key not in seed_data:
                seed_data[key] = value
                print(f"  {C.G}✓{C.E} Generated {key}")

    except Exception as e:
        print(f"{C.R}AI expansion failed: {e}{C.E}")
        print(f"{C.W}Continuing with provided data only.{C.E}")

    return seed_data


# ============================================================================
# Project Creation
# ============================================================================

def create_project_from_seed(seed_data: Dict[str, Any], project_name: str = None) -> Path:
    """Create a project directory from expanded seed data."""

    # Generate project name if not provided
    if not project_name:
        title = seed_data.get('TITLE', seed_data.get('IDEA', 'untitled')[:30])
        project_name = title.lower().replace(' ', '-').replace("'", "")
        # Clean up
        import re
        project_name = re.sub(r'[^a-z0-9-]', '', project_name)

    # Create project directory
    projects_dir = PROJECT_ROOT / "data" / "projects"
    project_dir = projects_dir / project_name
    project_dir.mkdir(parents=True, exist_ok=True)

    # Create subdirectories
    (project_dir / "drafts").mkdir(exist_ok=True)
    (project_dir / "output").mkdir(exist_ok=True)
    (project_dir / "memory").mkdir(exist_ok=True)

    # Map seed data to project config
    config = {
        "project_name": project_name,
        "title": seed_data.get('TITLE', seed_data.get('IDEA', '')[:50]),
        "genre": seed_data.get('GENRE', 'literary'),
        "tone": seed_data.get('TONE', ''),
        "target_length": seed_data.get('TARGET_LENGTH', 'standard (60k)'),
        "synopsis": seed_data.get('IDEA', ''),

        "setting": seed_data.get('SETTING', ''),
        "world_rules": seed_data.get('WORLD_RULES', ''),
        "key_locations": seed_data.get('KEY_LOCATIONS', ''),

        "protagonist": seed_data.get('PROTAGONIST', ''),
        "antagonist": seed_data.get('ANTAGONIST', ''),
        "other_characters": seed_data.get('OTHER_CHARACTERS', ''),

        "premise": seed_data.get('PREMISE', ''),
        "central_conflict": seed_data.get('CENTRAL_CONFLICT', ''),
        "key_plot_points": seed_data.get('KEY_PLOT_POINTS', ''),
        "subplots": seed_data.get('SUBPLOTS', ''),

        "themes": seed_data.get('THEMES', ''),
        "central_question": seed_data.get('CENTRAL_QUESTION', ''),
        "motifs": seed_data.get('MOTIFS', ''),

        "writing_style": seed_data.get('WRITING_STYLE', ''),
        "influences": seed_data.get('INFLUENCES', ''),
        "avoid": seed_data.get('AVOID', ''),

        "budget_usd": 0,
        "model_defaults": {
            "local_model": "qwen2.5:7b",
            "api_model": "qwen2.5:7b",
            "critic_model": "qwen2.5:7b",
            "fallback_model": "qwen2.5:7b"
        },
        "stage_model_map": {
            "high_concept": "api_model",
            "beat_sheet": "api_model",
            "write_scene": "api_model",
            "self_refine": "critic_model"
        },
        "status": "seeded"
    }

    # Parse and inject strategic guidance sub-fields
    strategic_raw = seed_data.get('STRATEGIC_GUIDANCE', '')
    if strategic_raw:
        strategic_guidance = _parse_strategic_guidance(strategic_raw)
        if strategic_guidance:
            config["strategic_guidance"] = strategic_guidance

    # Save config
    config_file = project_dir / "config.yaml"
    with open(config_file, "w", encoding="utf-8") as f:
        yaml.dump(config, f, default_flow_style=False, allow_unicode=True)

    # Save raw seed data for reference
    seed_file = project_dir / "seed_data.yaml"
    with open(seed_file, "w", encoding="utf-8") as f:
        yaml.dump(seed_data, f, default_flow_style=False, allow_unicode=True)

    return project_dir


# ============================================================================
# Main Entry Point
# ============================================================================

async def run_seed_interactive():
    """Run the interactive seed process."""
    print_banner()

    while True:
        print_mode_menu()
        choice = input(f"{C.G}Select mode (1/2/3/T/Q): {C.E}").strip().upper()

        if choice == 'Q':
            print(f"{C.DIM}Goodbye!{C.E}")
            return None

        if choice == 'T':
            print_template()
            input(f"\n{C.W}Press Enter to continue...{C.E}")
            continue

        if choice == '1':
            seed_data = full_mode()
        elif choice == '2':
            seed_data = guided_mode()
        elif choice == '3':
            seed_data = minimal_mode()
        else:
            print(f"{C.R}Invalid choice. Try again.{C.E}")
            continue

        # Validate
        valid, msg = validate_seed(seed_data)
        if not valid:
            print(f"\n{C.R}Error: {msg}{C.E}")
            continue

        # Show summary
        print_summary(seed_data)

        # Ask about AI expansion
        if len(seed_data) < len(TEMPLATE_SECTIONS):
            expand = input(f"{C.B}Expand missing sections with AI? (Y/n): {C.E}").strip().lower()
            if expand != 'n':
                seed_data = await expand_seed(seed_data)
                print_summary(seed_data)

        # Confirm and create project
        proceed = input(f"{C.G}Create project from this seed? (Y/n): {C.E}").strip().lower()
        if proceed == 'n':
            continue

        project_dir = create_project_from_seed(seed_data)

        print(f"\n{C.G}{'='*60}{C.E}")
        print(f"{C.BOLD}PROJECT CREATED!{C.E}")
        print(f"{C.G}{'='*60}{C.E}")
        print(f"\n  Location: {C.C}{project_dir}{C.E}")
        print(f"  Config:   {C.C}{project_dir / 'config.yaml'}{C.E}")
        print(f"\n{C.B}Next steps:{C.E}")
        print(f"  1. Review: {C.DIM}cat {project_dir / 'config.yaml'}{C.E}")
        print(f"  2. Generate: {C.DIM}python -m prometheus_novel.interfaces.cli.main generate -c {project_dir / 'config.yaml'}{C.E}")
        print()

        return project_dir


def main():
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        prog="writerai-seed",
        description="Seed a new novel project with flexible input"
    )
    parser.add_argument("--mode", choices=["full", "guided", "minimal"],
                        help="Skip menu and use specified mode")
    parser.add_argument("--file", "-f", type=Path,
                        help="Load seed from file (template format)")
    parser.add_argument("--no-expand", action="store_true",
                        help="Don't use AI to expand missing sections")

    args = parser.parse_args()

    if args.file:
        # File mode - parse and create directly
        if not args.file.exists():
            print(f"{C.R}File not found: {args.file}{C.E}")
            return 1

        text = args.file.read_text(encoding="utf-8")
        seed_data = parse_template_input(text)

        valid, msg = validate_seed(seed_data)
        if not valid:
            print(f"{C.R}Error: {msg}{C.E}")
            return 1

        print_summary(seed_data)

        if not args.no_expand and len(seed_data) < len(TEMPLATE_SECTIONS):
            seed_data = asyncio.run(expand_seed(seed_data))

        project_dir = create_project_from_seed(seed_data)
        print(f"{C.G}Project created: {project_dir}{C.E}")
        return 0

    # Interactive mode
    asyncio.run(run_seed_interactive())
    return 0


if __name__ == "__main__":
    sys.exit(main())
